[book]
title = "UAV Austin Documentation"
author = "UAV Austin"

[output.html]
mathjax-support = true
no-section-label = true
default-theme = navy

[build]
build-dir = "../book"
create-missing = false
